
Business.create!([
  {title: "xkcd.com", rss_feed_url: "http://xkcd.com/rss.xml", description: "lol", category_id: nil, image_source: "xkcd.png"},
  {title: "Dinosaur Comics", rss_feed_url: "http://www.qwantz.com/rssfeed.php", description: "Dinosaur Comics!", category_id: nil, image_source: "Dinosaur_Comics.jpg"},
  {title: "Explosm.net", rss_feed_url: "http://feeds.feedburner.com/Explosm", description: "Cyanide and Happiness!", category_id: nil, image_source: "explosm-logo.jpeg"},
  {title: "Lifehacker.com", rss_feed_url: "http://feeds.gawker.com/lifehacker/full", description: "Hack your life", category_id: nil, image_source: "Lifehacker_Logo.png"},
  {title: "TechCrunch Startups", rss_feed_url: "http://feeds.feedburner.com/TechCrunch/startups", description: "All the news you need on startups", category_id: nil, image_source: "tc-logo.jpg"},
  {title: "Kotaku", rss_feed_url: "http://feeds.gawker.com/kotaku/full", description: "Your source for video game debauchery", category_id: nil, image_source: "kotakuLogo.png"},
  {title: "Harvard Business Review", rss_feed_url: "http://hbswk.hbs.edu/rss/rss.xml", description: "The Harvard Business Review", category_id: nil, image_source: "HarvardBusinessReviewlogo.png"},
  {title: "The Business of Fashion", rss_feed_url: "http://www.businessoffashion.com/feed", description: "Fashion News, Analysis and Business Intelligence from the leading digital authority", category_id: nil, image_source: "bof_logo.png"},
  {title: "Seth Godin", rss_feed_url: "http://feeds.feedblitz.com/sethsblog&x=1", description: "Seth Godin's riffs on marketing, respect, and the ways ideas spread.", category_id: nil, image_source: "seth-godin.png"},
  {title: "Calculated Risk", rss_feed_url: "http://feeds.feedburner.com/CalculatedRisk", description: "A top ranked economics and finance blog with a focus on the housing market", category_id: nil, image_source: "calculated-risk.jpeg"},
  {title: "Entrepreneur: Latest Articles", rss_feed_url: "http://feeds.feedburner.com/entrepreneur/latest", description: "The latest small business tips and advice from Entrepreneur.com", category_id: nil, image_source: "entrepreneur_media_logo_20121.jpg"},
  {title: "The Atlantic", rss_feed_url: "http://feeds.feedburner.com/TheAtlantic", description: "The Atlantic covers breaking news, analysis, opinion around the intersection of Washington and Wall Street.", category_id: nil, image_source: "TheAtlanticlogo.png"},
  {title: "Fast Company", rss_feed_url: "http://feeds.feedburner.com/fastcompany/headlines", description: "Fast Company inspires a new breed of innovative and creative thought.", category_id: nil, image_source: "fast-company-logo-300x300.gif"},
  {title: "The Verge", rss_feed_url: "http://www.theverge.com/rss/index.xml", description: "The Verge was founded in 2011 in partnership with Vox Media, and covers the intersection of technology, science, art, and culture.", category_id: nil, image_source: "The_Verge_logo.svg.png"},
  {title: "Gizmodo", rss_feed_url: "http://feeds.gawker.com/gizmodo/full", description: "Tech by Design", category_id: nil, image_source: "gizmodo-logo-sm.jpg"},
  {title: "Mashable", rss_feed_url: "http://feeds.mashable.com/Mashable", description: "Mashable is a leading source for news, information & resources for the Connected Generation.", category_id: nil, image_source: "mashable-logo.png"},
  {title: "Wired: Top Stories", rss_feed_url: "http://feeds.wired.com/wired/index", description: "Get in-depth coverage of current and future trends in technology", category_id: nil, image_source: "wired_logo.jpg"},
  {title: "The Official Google Blog", rss_feed_url: "http://feeds.feedburner.com/blogspot/MKuf", description: "Insights from Googlers into our products, technology, and the Google culture.", category_id: nil, image_source: "Google_logo.png"},
  {title: "Tesla Motors - Financial  Releases", rss_feed_url: "http://apps.shareholder.com/rss/rss.aspx?channels=7196&companyid=ABEA-4CW8X0&sh_auth=3665213721%2E0%2E0%2E41970%2E199b163d0e2a0e1270030654c2099d8d", description: "An electric car company", category_id: 1, image_source: "tesla-logo.jpg"},
  {title: "Walmart Corporate: All News", rss_feed_url: "http://news.walmart.com/rss?feedName=allnews", description: "The megalithic company", category_id: nil, image_source: "walmart-logo-sun55.jpg"},
  {title: "GM Media News", rss_feed_url: "http://media.gmc.com/media/us/en/gmc/news/jcr:content/categorynavigation/subcategorynavigation/rss.newsrss.html", description: "A division of the American manufacturer General Motors (GM)", category_id: 1, image_source: "gmc-trucks-logo-emblem.jpg"},
])

